domain_path: C:\Users\mpaur\.Xilinx\PruebaVitis\project_clp\vitis_wsp_TCP\SecondPlatform\export\SecondPlatform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2024.1\data\embeddedsw\lib\sw_apps\lwip_tcp_perf_client
template: lwip_tcp_perf_client
