# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/mpaur/.Xilinx/PruebaVitis/project_clp/Arty-Z7-20-Master.xdc

# Block Designs: bd/blq_top/blq_top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blq_top || ORIG_REF_NAME==blq_top} -quiet] -quiet

# IP: bd/blq_top/ip/blq_top_processing_system7_0_0/blq_top_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blq_top_processing_system7_0_0 || ORIG_REF_NAME==blq_top_processing_system7_0_0} -quiet] -quiet

# IP: bd/blq_top/ip/blq_top_axi_gpio_0_0/blq_top_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blq_top_axi_gpio_0_0 || ORIG_REF_NAME==blq_top_axi_gpio_0_0} -quiet] -quiet

# IP: bd/blq_top/ip/blq_top_xbar_0/blq_top_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blq_top_xbar_0 || ORIG_REF_NAME==blq_top_xbar_0} -quiet] -quiet

# IP: bd/blq_top/ip/blq_top_ps7_0_axi_periph_0/blq_top_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blq_top_ps7_0_axi_periph_0 || ORIG_REF_NAME==blq_top_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/blq_top/ip/blq_top_rst_ps7_0_100M_0/blq_top_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blq_top_rst_ps7_0_100M_0 || ORIG_REF_NAME==blq_top_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/blq_top/ip/blq_top_axi_gpio_1_0/blq_top_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blq_top_axi_gpio_1_0 || ORIG_REF_NAME==blq_top_axi_gpio_1_0} -quiet] -quiet

# IP: bd/blq_top/ip/blq_top_axi_gpio_2_0/blq_top_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blq_top_axi_gpio_2_0 || ORIG_REF_NAME==blq_top_axi_gpio_2_0} -quiet] -quiet

# IP: bd/blq_top/ip/blq_top_axi_gpio_3_0/blq_top_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blq_top_axi_gpio_3_0 || ORIG_REF_NAME==blq_top_axi_gpio_3_0} -quiet] -quiet

# IP: bd/blq_top/ip/blq_top_axi_gpio_4_0/blq_top_axi_gpio_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blq_top_axi_gpio_4_0 || ORIG_REF_NAME==blq_top_axi_gpio_4_0} -quiet] -quiet

# IP: bd/blq_top/ip/blq_top_LMX2594_0_0/blq_top_LMX2594_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blq_top_LMX2594_0_0 || ORIG_REF_NAME==blq_top_LMX2594_0_0} -quiet] -quiet

# IP: bd/blq_top/ip/blq_top_clk_wiz_0_0/blq_top_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blq_top_clk_wiz_0_0 || ORIG_REF_NAME==blq_top_clk_wiz_0_0} -quiet] -quiet

# IP: bd/blq_top/ip/blq_top_auto_pc_0/blq_top_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blq_top_auto_pc_0 || ORIG_REF_NAME==blq_top_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/mpaur/.Xilinx/PruebaVitis/project_clp/project_vhdl.gen/sources_1/bd/blq_top/blq_top_ooc.xdc
