# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mpaur/.Xilinx/PruebaVitis/project_clp/project_vhdl.srcs/sources_1/bd/blq_top/ip/blq_top_clk_wiz_0_0/blq_top_clk_wiz_0_0.xci
# IP: The module: 'blq_top_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mpaur/.Xilinx/PruebaVitis/project_clp/project_vhdl.gen/sources_1/bd/blq_top/ip/blq_top_clk_wiz_0_0/blq_top_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'blq_top_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/mpaur/.Xilinx/PruebaVitis/project_clp/project_vhdl.gen/sources_1/bd/blq_top/ip/blq_top_clk_wiz_0_0/blq_top_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'blq_top_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/mpaur/.Xilinx/PruebaVitis/project_clp/project_vhdl.gen/sources_1/bd/blq_top/ip/blq_top_clk_wiz_0_0/blq_top_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blq_top_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/mpaur/.Xilinx/PruebaVitis/project_clp/project_vhdl.srcs/sources_1/bd/blq_top/ip/blq_top_clk_wiz_0_0/blq_top_clk_wiz_0_0.xci
# IP: The module: 'blq_top_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mpaur/.Xilinx/PruebaVitis/project_clp/project_vhdl.gen/sources_1/bd/blq_top/ip/blq_top_clk_wiz_0_0/blq_top_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'blq_top_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/mpaur/.Xilinx/PruebaVitis/project_clp/project_vhdl.gen/sources_1/bd/blq_top/ip/blq_top_clk_wiz_0_0/blq_top_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'blq_top_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/mpaur/.Xilinx/PruebaVitis/project_clp/project_vhdl.gen/sources_1/bd/blq_top/ip/blq_top_clk_wiz_0_0/blq_top_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blq_top_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
