# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/PruebaVivado/Arty-Z7-20-Master.xdc

# Block Designs: bd/PruebaTOP/PruebaTOP.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PruebaTOP || ORIG_REF_NAME==PruebaTOP} -quiet] -quiet

# IP: bd/PruebaTOP/ip/PruebaTOP_LMX2594_0_0/PruebaTOP_LMX2594_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PruebaTOP_LMX2594_0_0 || ORIG_REF_NAME==PruebaTOP_LMX2594_0_0} -quiet] -quiet

# IP: bd/PruebaTOP/ip/PruebaTOP_clk_wiz_0_0/PruebaTOP_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PruebaTOP_clk_wiz_0_0 || ORIG_REF_NAME==PruebaTOP_clk_wiz_0_0} -quiet] -quiet

# IP: bd/PruebaTOP/ip/PruebaTOP_xlconstant_0_0/PruebaTOP_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PruebaTOP_xlconstant_0_0 || ORIG_REF_NAME==PruebaTOP_xlconstant_0_0} -quiet] -quiet

# IP: bd/PruebaTOP/ip/PruebaTOP_xlconstant_0_1/PruebaTOP_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PruebaTOP_xlconstant_0_1 || ORIG_REF_NAME==PruebaTOP_xlconstant_0_1} -quiet] -quiet

# XDC: c:/Users/mpaur/MESE/CLP/GuiaPracticaCLP/SPI_TPF/PruebaVivado/PruebaVivado.gen/sources_1/bd/PruebaTOP/PruebaTOP_ooc.xdc
